### ISSUE TITLE
[Feature Request] 64-bit support

### ISSUE THREAD

**Issue by SSS-mode** [uyjulian/ifavif#1]
First, I want to thank you for this much needed susie plugin, it works perfectly in 32-bit programs.

I wonder would it be possible be converted to a 64-bit format, for some of programs only support 64-bit susie plugins. Please give it some thought, thank you in advance.

**Comment by uyjulian** [comment]
Sure, that can be possible. I'll do it when I have free time.

**Comment by uyjulian** [comment]
64-bit is now supported! Download from here: https://github.com/uyjulian/ifavif/releases/latest/download/ifavif.intel64.gcc.7z

**Comment by SSS-mode** [comment]
Thank you so much! It works flawlessly, great job!
